# Generated by Django 4.0.4 on 2022-09-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
