# Generated by Django 4.0.4 on 2022-09-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='realese_date',
            field=models.DateField(verbose_name='Fecha de Estreno'),
        ),
    ]
