# Generated by Django 4.0.4 on 2022-09-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_realese_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='clasification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.age'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='genero',
        ),
        migrations.AddField(
            model_name='film',
            name='genero',
            field=models.ManyToManyField(to='films.gener', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='films'),
        ),
    ]
